/* Generated by Yosys 0.51+85 (git sha1 d3aec12fe, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "spi.v:24.1-101.10" *)
module spi(clk, rst, ss, mosi, miso, sck, done, din, dout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  (* force_downto = 32'd1 *)
  (* src = "spi.v:68.20-68.35|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* src = "spi.v:42.23-42.31" *)
  wire [2:0] bit_ct_q;
  (* src = "spi.v:25.11-25.14" *)
  input clk;
  wire clk;
  (* src = "spi.v:40.21-40.27" *)
  wire [7:0] data_q;
  (* src = "spi.v:32.17-32.20" *)
  input [7:0] din;
  wire [7:0] din;
  (* src = "spi.v:31.12-31.16" *)
  output done;
  wire done;
  (* src = "spi.v:41.15-41.21" *)
  wire done_q;
  (* src = "spi.v:33.18-33.22" *)
  output [7:0] dout;
  wire [7:0] dout;
  (* src = "spi.v:43.21-43.27" *)
  wire [7:0] dout_q;
  (* src = "spi.v:29.12-29.16" *)
  output miso;
  wire miso;
  (* src = "spi.v:44.7-44.13" *)
  wire miso_d;
  (* src = "spi.v:44.15-44.21" *)
  wire miso_q;
  (* src = "spi.v:28.11-28.15" *)
  input mosi;
  wire mosi;
  (* src = "spi.v:36.7-36.13" *)
  wire mosi_d;
  (* src = "spi.v:36.15-36.21" *)
  wire mosi_q;
  (* src = "spi.v:26.11-26.14" *)
  input rst;
  wire rst;
  (* src = "spi.v:30.11-30.14" *)
  input sck;
  wire sck;
  (* src = "spi.v:38.7-38.12" *)
  wire sck_d;
  (* src = "spi.v:39.7-39.16" *)
  wire sck_old_d;
  (* src = "spi.v:39.18-39.27" *)
  wire sck_old_q;
  (* src = "spi.v:38.14-38.19" *)
  wire sck_q;
  (* src = "spi.v:27.11-27.13" *)
  input ss;
  wire ss;
  (* src = "spi.v:37.7-37.11" *)
  wire ss_d;
  (* src = "spi.v:37.13-37.17" *)
  wire ss_q;
  sg13g2_inv_1 _087_ (
    .A(data_q[7]),
    .Y(_032_)
  );
  sg13g2_inv_1 _088_ (
    .A(bit_ct_q[0]),
    .Y(_033_)
  );
  sg13g2_inv_1 _089_ (
    .A(sck_q),
    .Y(_034_)
  );
  sg13g2_nor2b_1 _090_ (
    .A(sck_old_q),
    .B_N(sck_q),
    .Y(_035_)
  );
  sg13g2_nand2b_1 _091_ (
    .A_N(sck_old_q),
    .B(sck_q),
    .Y(_036_)
  );
  sg13g2_nor2_1 _092_ (
    .A(ss_q),
    .B(_035_),
    .Y(_037_)
  );
  sg13g2_nand3_1 _093_ (
    .A(bit_ct_q[2]),
    .B(bit_ct_q[1]),
    .C(bit_ct_q[0]),
    .Y(_038_)
  );
  sg13g2_nor2b_1 _094_ (
    .A(ss_q),
    .B_N(_038_),
    .Y(_039_)
  );
  sg13g2_mux2_1 _095_ (
    .A0(din[0]),
    .A1(mosi_q),
    .S(_039_),
    .X(_040_)
  );
  sg13g2_mux2_1 _096_ (
    .A0(_040_),
    .A1(data_q[0]),
    .S(_037_),
    .X(_000_)
  );
  sg13g2_mux2_1 _097_ (
    .A0(din[1]),
    .A1(data_q[0]),
    .S(_039_),
    .X(_041_)
  );
  sg13g2_mux2_1 _098_ (
    .A0(_041_),
    .A1(data_q[1]),
    .S(_037_),
    .X(_001_)
  );
  sg13g2_mux2_1 _099_ (
    .A0(din[2]),
    .A1(data_q[1]),
    .S(_039_),
    .X(_042_)
  );
  sg13g2_mux2_1 _100_ (
    .A0(_042_),
    .A1(data_q[2]),
    .S(_037_),
    .X(_002_)
  );
  sg13g2_mux2_1 _101_ (
    .A0(din[3]),
    .A1(data_q[2]),
    .S(_039_),
    .X(_043_)
  );
  sg13g2_mux2_1 _102_ (
    .A0(_043_),
    .A1(data_q[3]),
    .S(_037_),
    .X(_003_)
  );
  sg13g2_mux2_1 _103_ (
    .A0(din[4]),
    .A1(data_q[3]),
    .S(_039_),
    .X(_044_)
  );
  sg13g2_mux2_1 _104_ (
    .A0(_044_),
    .A1(data_q[4]),
    .S(_037_),
    .X(_004_)
  );
  sg13g2_mux2_1 _105_ (
    .A0(din[5]),
    .A1(data_q[4]),
    .S(_039_),
    .X(_045_)
  );
  sg13g2_mux2_1 _106_ (
    .A0(_045_),
    .A1(data_q[5]),
    .S(_037_),
    .X(_005_)
  );
  sg13g2_mux2_1 _107_ (
    .A0(din[6]),
    .A1(data_q[5]),
    .S(_039_),
    .X(_046_)
  );
  sg13g2_mux2_1 _108_ (
    .A0(_046_),
    .A1(data_q[6]),
    .S(_037_),
    .X(_006_)
  );
  sg13g2_mux2_1 _109_ (
    .A0(din[7]),
    .A1(data_q[6]),
    .S(_039_),
    .X(_047_)
  );
  sg13g2_mux2_1 _110_ (
    .A0(_047_),
    .A1(data_q[7]),
    .S(_037_),
    .X(_007_)
  );
  sg13g2_nor2_1 _111_ (
    .A(ss_q),
    .B(rst),
    .Y(_048_)
  );
  sg13g2_o21ai_1 _112_ (
    .A1(_062_[0]),
    .A2(_036_),
    .B1(_048_),
    .Y(_049_)
  );
  sg13g2_a21oi_1 _113_ (
    .A1(_033_),
    .A2(_036_),
    .B1(_049_),
    .Y(_008_)
  );
  sg13g2_and3_1 _114_ (
    .A(bit_ct_q[1]),
    .B(bit_ct_q[0]),
    .C(_035_),
    .X(_050_)
  );
  sg13g2_a21oi_1 _115_ (
    .A1(bit_ct_q[0]),
    .A2(_035_),
    .B1(bit_ct_q[1]),
    .Y(_051_)
  );
  sg13g2_nor4_1 _116_ (
    .A(ss_q),
    .B(rst),
    .C(_050_),
    .D(_051_),
    .Y(_009_)
  );
  sg13g2_o21ai_1 _117_ (
    .A1(bit_ct_q[2]),
    .A2(_050_),
    .B1(_048_),
    .Y(_052_)
  );
  sg13g2_a21oi_1 _118_ (
    .A1(bit_ct_q[2]),
    .A2(_050_),
    .B1(_052_),
    .Y(_010_)
  );
  sg13g2_nor3_1 _119_ (
    .A(ss_q),
    .B(_036_),
    .C(_038_),
    .Y(_053_)
  );
  sg13g2_or3_1 _120_ (
    .A(ss_q),
    .B(_036_),
    .C(_038_),
    .X(_054_)
  );
  sg13g2_nand2_1 _121_ (
    .A(mosi_q),
    .B(_053_),
    .Y(_055_)
  );
  sg13g2_nand2_1 _122_ (
    .A(dout_q[0]),
    .B(_054_),
    .Y(_056_)
  );
  sg13g2_a21oi_1 _123_ (
    .A1(_055_),
    .A2(_056_),
    .B1(rst),
    .Y(_011_)
  );
  sg13g2_nand2_1 _124_ (
    .A(data_q[0]),
    .B(_053_),
    .Y(_057_)
  );
  sg13g2_nand2_1 _125_ (
    .A(dout_q[1]),
    .B(_054_),
    .Y(_058_)
  );
  sg13g2_a21oi_1 _126_ (
    .A1(_057_),
    .A2(_058_),
    .B1(rst),
    .Y(_012_)
  );
  sg13g2_nand2_1 _127_ (
    .A(data_q[1]),
    .B(_053_),
    .Y(_059_)
  );
  sg13g2_nand2_1 _128_ (
    .A(dout_q[2]),
    .B(_054_),
    .Y(_060_)
  );
  sg13g2_a21oi_1 _129_ (
    .A1(_059_),
    .A2(_060_),
    .B1(rst),
    .Y(_013_)
  );
  sg13g2_nand2_1 _130_ (
    .A(data_q[2]),
    .B(_053_),
    .Y(_061_)
  );
  sg13g2_nand2_1 _131_ (
    .A(dout_q[3]),
    .B(_054_),
    .Y(_021_)
  );
  sg13g2_a21oi_1 _132_ (
    .A1(_061_),
    .A2(_021_),
    .B1(rst),
    .Y(_014_)
  );
  sg13g2_nand2_1 _133_ (
    .A(data_q[3]),
    .B(_053_),
    .Y(_022_)
  );
  sg13g2_nand2_1 _134_ (
    .A(dout_q[4]),
    .B(_054_),
    .Y(_023_)
  );
  sg13g2_a21oi_1 _135_ (
    .A1(_022_),
    .A2(_023_),
    .B1(rst),
    .Y(_015_)
  );
  sg13g2_nand2_1 _136_ (
    .A(data_q[4]),
    .B(_053_),
    .Y(_024_)
  );
  sg13g2_nand2_1 _137_ (
    .A(dout_q[5]),
    .B(_054_),
    .Y(_025_)
  );
  sg13g2_a21oi_1 _138_ (
    .A1(_024_),
    .A2(_025_),
    .B1(rst),
    .Y(_016_)
  );
  sg13g2_nand2_1 _139_ (
    .A(data_q[5]),
    .B(_053_),
    .Y(_026_)
  );
  sg13g2_nand2_1 _140_ (
    .A(dout_q[6]),
    .B(_054_),
    .Y(_027_)
  );
  sg13g2_a21oi_1 _141_ (
    .A1(_026_),
    .A2(_027_),
    .B1(rst),
    .Y(_017_)
  );
  sg13g2_nand2_1 _142_ (
    .A(data_q[6]),
    .B(_053_),
    .Y(_028_)
  );
  sg13g2_nand2_1 _143_ (
    .A(dout_q[7]),
    .B(_054_),
    .Y(_029_)
  );
  sg13g2_a21oi_1 _144_ (
    .A1(_028_),
    .A2(_029_),
    .B1(rst),
    .Y(_018_)
  );
  sg13g2_a21oi_1 _145_ (
    .A1(_034_),
    .A2(sck_old_q),
    .B1(ss_q),
    .Y(_030_)
  );
  sg13g2_a21oi_1 _146_ (
    .A1(miso_q),
    .A2(_030_),
    .B1(rst),
    .Y(_031_)
  );
  sg13g2_o21ai_1 _147_ (
    .A1(_032_),
    .A2(_030_),
    .B1(_031_),
    .Y(_019_)
  );
  sg13g2_nor2_1 _148_ (
    .A(rst),
    .B(_054_),
    .Y(_020_)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _149_ (
    .CLK(clk),
    .D(_000_),
    .Q(data_q[0]),
    .Q_N(_082_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _150_ (
    .CLK(clk),
    .D(_001_),
    .Q(data_q[1]),
    .Q_N(_081_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _151_ (
    .CLK(clk),
    .D(_002_),
    .Q(data_q[2]),
    .Q_N(_080_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _152_ (
    .CLK(clk),
    .D(_003_),
    .Q(data_q[3]),
    .Q_N(_079_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _153_ (
    .CLK(clk),
    .D(_004_),
    .Q(data_q[4]),
    .Q_N(_078_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _154_ (
    .CLK(clk),
    .D(_005_),
    .Q(data_q[5]),
    .Q_N(_077_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _155_ (
    .CLK(clk),
    .D(_006_),
    .Q(data_q[6]),
    .Q_N(_076_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _156_ (
    .CLK(clk),
    .D(_007_),
    .Q(data_q[7]),
    .Q_N(_083_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _157_ (
    .CLK(clk),
    .D(sck),
    .Q(sck_q),
    .Q_N(_075_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _158_ (
    .CLK(clk),
    .D(_008_),
    .Q(bit_ct_q[0]),
    .Q_N(_062_[0]),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _159_ (
    .CLK(clk),
    .D(_009_),
    .Q(bit_ct_q[1]),
    .Q_N(_074_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _160_ (
    .CLK(clk),
    .D(_010_),
    .Q(bit_ct_q[2]),
    .Q_N(_073_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _161_ (
    .CLK(clk),
    .D(_011_),
    .Q(dout_q[0]),
    .Q_N(_072_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _162_ (
    .CLK(clk),
    .D(_012_),
    .Q(dout_q[1]),
    .Q_N(_071_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _163_ (
    .CLK(clk),
    .D(_013_),
    .Q(dout_q[2]),
    .Q_N(_070_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _164_ (
    .CLK(clk),
    .D(_014_),
    .Q(dout_q[3]),
    .Q_N(_069_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _165_ (
    .CLK(clk),
    .D(_015_),
    .Q(dout_q[4]),
    .Q_N(_068_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _166_ (
    .CLK(clk),
    .D(_016_),
    .Q(dout_q[5]),
    .Q_N(_067_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _167_ (
    .CLK(clk),
    .D(_017_),
    .Q(dout_q[6]),
    .Q_N(_066_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _168_ (
    .CLK(clk),
    .D(_018_),
    .Q(dout_q[7]),
    .Q_N(_065_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _169_ (
    .CLK(clk),
    .D(_019_),
    .Q(miso_q),
    .Q_N(_084_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _170_ (
    .CLK(clk),
    .D(ss),
    .Q(ss_q),
    .Q_N(_064_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _171_ (
    .CLK(clk),
    .D(_020_),
    .Q(done_q),
    .Q_N(_085_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _172_ (
    .CLK(clk),
    .D(mosi),
    .Q(mosi_q),
    .Q_N(_086_),
    .RESET_B(1'h1)
  );
  (* src = "spi.v:80.3-99.6" *)
  sg13g2_dfrbp_1 _173_ (
    .CLK(clk),
    .D(sck_q),
    .Q(sck_old_q),
    .Q_N(_063_),
    .RESET_B(1'h1)
  );
  assign _062_[2:1] = bit_ct_q[2:1];
  assign done = done_q;
  assign dout = dout_q;
  assign miso = miso_q;
  assign miso_d = data_q[7];
  assign mosi_d = mosi;
  assign sck_d = sck;
  assign sck_old_d = sck_q;
  assign ss_d = ss;
endmodule
